import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Image from "next/image";
import Logo from "../public/Remove-bg.ai_1702092397401.png"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Zooor Obed",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="div">
          <div className="max-w-screen-2xl mx-auto p-4">
            <div className="flex justify-center">
              <div className="flex justify-center bg-white w-2/12 rounded-full">
                <Image src={Logo} alt="Image" width={250} height={100} />
              </div>
            </div>
            <Navbar />
            <div className="mt-8">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
